name: lambda_timeline
description: A flutter app that shows Lambda School's curriculum.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/fullstackweb.png
   - assets/images/ios.png
   - assets/images/android.png
   - assets/images/data.png
   - assets/images/design.png
   - assets/images/learntocode.png
   - assets/images/lambdalove.png

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
          weight: 400
    - family: PT Sans
      fonts:
        - asset: assets/fonts/PT_Sans-Web-Regular.ttf
          weight: 400
        - asset: assets/fonts/PT_Sans-Web-Bold.ttf
          weight: 700
